#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hairoscope_Service
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database1")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUserRegistration(UserRegistration instance);
    partial void UpdateUserRegistration(UserRegistration instance);
    partial void DeleteUserRegistration(UserRegistration instance);
    partial void InsertCart(Cart instance);
    partial void UpdateCart(Cart instance);
    partial void DeleteCart(Cart instance);
    partial void InsertProduct(Product instance);
    partial void UpdateProduct(Product instance);
    partial void DeleteProduct(Product instance);
    partial void InsertWishLIst(WishLIst instance);
    partial void UpdateWishLIst(WishLIst instance);
    partial void DeleteWishLIst(WishLIst instance);
    partial void InsertInvoice(Invoice instance);
    partial void UpdateInvoice(Invoice instance);
    partial void DeleteInvoice(Invoice instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Database1ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<UserRegistration> UserRegistrations
		{
			get
			{
				return this.GetTable<UserRegistration>();
			}
		}
		
		public System.Data.Linq.Table<Cart> Carts
		{
			get
			{
				return this.GetTable<Cart>();
			}
		}
		
		public System.Data.Linq.Table<Product> Products
		{
			get
			{
				return this.GetTable<Product>();
			}
		}
		
		public System.Data.Linq.Table<WishLIst> WishLIsts
		{
			get
			{
				return this.GetTable<WishLIst>();
			}
		}
		
		public System.Data.Linq.Table<Invoice> Invoices
		{
			get
			{
				return this.GetTable<Invoice>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserRegistration")]
	public partial class UserRegistration : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _US_Id;
		
		private string _US_Name;
		
		private string _US_SurName;
		
		private string _US_Email;
		
		private string _US_Password;
		
		private string _US_Type;
		
		private string _US_ID_NUM;
		
		private System.Nullable<System.DateTime> _US_DATE_OF_BIRTH;
		
		private string _US_CONTACT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUS_IdChanging(int value);
    partial void OnUS_IdChanged();
    partial void OnUS_NameChanging(string value);
    partial void OnUS_NameChanged();
    partial void OnUS_SurNameChanging(string value);
    partial void OnUS_SurNameChanged();
    partial void OnUS_EmailChanging(string value);
    partial void OnUS_EmailChanged();
    partial void OnUS_PasswordChanging(string value);
    partial void OnUS_PasswordChanged();
    partial void OnUS_TypeChanging(string value);
    partial void OnUS_TypeChanged();
    partial void OnUS_ID_NUMChanging(string value);
    partial void OnUS_ID_NUMChanged();
    partial void OnUS_DATE_OF_BIRTHChanging(System.Nullable<System.DateTime> value);
    partial void OnUS_DATE_OF_BIRTHChanged();
    partial void OnUS_CONTACTChanging(string value);
    partial void OnUS_CONTACTChanged();
    #endregion
		
		public UserRegistration()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_US_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int US_Id
		{
			get
			{
				return this._US_Id;
			}
			set
			{
				if ((this._US_Id != value))
				{
					this.OnUS_IdChanging(value);
					this.SendPropertyChanging();
					this._US_Id = value;
					this.SendPropertyChanged("US_Id");
					this.OnUS_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_US_Name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string US_Name
		{
			get
			{
				return this._US_Name;
			}
			set
			{
				if ((this._US_Name != value))
				{
					this.OnUS_NameChanging(value);
					this.SendPropertyChanging();
					this._US_Name = value;
					this.SendPropertyChanged("US_Name");
					this.OnUS_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_US_SurName", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string US_SurName
		{
			get
			{
				return this._US_SurName;
			}
			set
			{
				if ((this._US_SurName != value))
				{
					this.OnUS_SurNameChanging(value);
					this.SendPropertyChanging();
					this._US_SurName = value;
					this.SendPropertyChanged("US_SurName");
					this.OnUS_SurNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_US_Email", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string US_Email
		{
			get
			{
				return this._US_Email;
			}
			set
			{
				if ((this._US_Email != value))
				{
					this.OnUS_EmailChanging(value);
					this.SendPropertyChanging();
					this._US_Email = value;
					this.SendPropertyChanged("US_Email");
					this.OnUS_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_US_Password", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string US_Password
		{
			get
			{
				return this._US_Password;
			}
			set
			{
				if ((this._US_Password != value))
				{
					this.OnUS_PasswordChanging(value);
					this.SendPropertyChanging();
					this._US_Password = value;
					this.SendPropertyChanged("US_Password");
					this.OnUS_PasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_US_Type", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string US_Type
		{
			get
			{
				return this._US_Type;
			}
			set
			{
				if ((this._US_Type != value))
				{
					this.OnUS_TypeChanging(value);
					this.SendPropertyChanging();
					this._US_Type = value;
					this.SendPropertyChanged("US_Type");
					this.OnUS_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_US_ID_NUM", DbType="VarChar(MAX)")]
		public string US_ID_NUM
		{
			get
			{
				return this._US_ID_NUM;
			}
			set
			{
				if ((this._US_ID_NUM != value))
				{
					this.OnUS_ID_NUMChanging(value);
					this.SendPropertyChanging();
					this._US_ID_NUM = value;
					this.SendPropertyChanged("US_ID_NUM");
					this.OnUS_ID_NUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_US_DATE_OF_BIRTH", DbType="Date")]
		public System.Nullable<System.DateTime> US_DATE_OF_BIRTH
		{
			get
			{
				return this._US_DATE_OF_BIRTH;
			}
			set
			{
				if ((this._US_DATE_OF_BIRTH != value))
				{
					this.OnUS_DATE_OF_BIRTHChanging(value);
					this.SendPropertyChanging();
					this._US_DATE_OF_BIRTH = value;
					this.SendPropertyChanged("US_DATE_OF_BIRTH");
					this.OnUS_DATE_OF_BIRTHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_US_CONTACT", DbType="Char(50)")]
		public string US_CONTACT
		{
			get
			{
				return this._US_CONTACT;
			}
			set
			{
				if ((this._US_CONTACT != value))
				{
					this.OnUS_CONTACTChanging(value);
					this.SendPropertyChanging();
					this._US_CONTACT = value;
					this.SendPropertyChanged("US_CONTACT");
					this.OnUS_CONTACTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cart")]
	public partial class Cart : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _C_Id;
		
		private int _P_Id;
		
		private int _Us_ID;
		
		private decimal _P_Price;
		
		private string _P_Img;
		
		private int _Quantity;
		
		private System.DateTime _DateAdded;
		
		private decimal _Tot_Price;
		
		private string _ProductName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnC_IdChanging(int value);
    partial void OnC_IdChanged();
    partial void OnP_IdChanging(int value);
    partial void OnP_IdChanged();
    partial void OnUs_IDChanging(int value);
    partial void OnUs_IDChanged();
    partial void OnP_PriceChanging(decimal value);
    partial void OnP_PriceChanged();
    partial void OnP_ImgChanging(string value);
    partial void OnP_ImgChanged();
    partial void OnQuantityChanging(int value);
    partial void OnQuantityChanged();
    partial void OnDateAddedChanging(System.DateTime value);
    partial void OnDateAddedChanged();
    partial void OnTot_PriceChanging(decimal value);
    partial void OnTot_PriceChanged();
    partial void OnProductNameChanging(string value);
    partial void OnProductNameChanged();
    #endregion
		
		public Cart()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int C_Id
		{
			get
			{
				return this._C_Id;
			}
			set
			{
				if ((this._C_Id != value))
				{
					this.OnC_IdChanging(value);
					this.SendPropertyChanging();
					this._C_Id = value;
					this.SendPropertyChanged("C_Id");
					this.OnC_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Id", DbType="Int NOT NULL")]
		public int P_Id
		{
			get
			{
				return this._P_Id;
			}
			set
			{
				if ((this._P_Id != value))
				{
					this.OnP_IdChanging(value);
					this.SendPropertyChanging();
					this._P_Id = value;
					this.SendPropertyChanged("P_Id");
					this.OnP_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Us_ID", DbType="Int NOT NULL")]
		public int Us_ID
		{
			get
			{
				return this._Us_ID;
			}
			set
			{
				if ((this._Us_ID != value))
				{
					this.OnUs_IDChanging(value);
					this.SendPropertyChanging();
					this._Us_ID = value;
					this.SendPropertyChanged("Us_ID");
					this.OnUs_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Price", DbType="Decimal(18,0) NOT NULL")]
		public decimal P_Price
		{
			get
			{
				return this._P_Price;
			}
			set
			{
				if ((this._P_Price != value))
				{
					this.OnP_PriceChanging(value);
					this.SendPropertyChanging();
					this._P_Price = value;
					this.SendPropertyChanged("P_Price");
					this.OnP_PriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Img", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string P_Img
		{
			get
			{
				return this._P_Img;
			}
			set
			{
				if ((this._P_Img != value))
				{
					this.OnP_ImgChanging(value);
					this.SendPropertyChanging();
					this._P_Img = value;
					this.SendPropertyChanged("P_Img");
					this.OnP_ImgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int NOT NULL")]
		public int Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateAdded", DbType="Date NOT NULL")]
		public System.DateTime DateAdded
		{
			get
			{
				return this._DateAdded;
			}
			set
			{
				if ((this._DateAdded != value))
				{
					this.OnDateAddedChanging(value);
					this.SendPropertyChanging();
					this._DateAdded = value;
					this.SendPropertyChanged("DateAdded");
					this.OnDateAddedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tot_Price", DbType="Decimal(18,0) NOT NULL")]
		public decimal Tot_Price
		{
			get
			{
				return this._Tot_Price;
			}
			set
			{
				if ((this._Tot_Price != value))
				{
					this.OnTot_PriceChanging(value);
					this.SendPropertyChanging();
					this._Tot_Price = value;
					this.SendPropertyChanged("Tot_Price");
					this.OnTot_PriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this.OnProductNameChanging(value);
					this.SendPropertyChanging();
					this._ProductName = value;
					this.SendPropertyChanged("ProductName");
					this.OnProductNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Products")]
	public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _P_Id;
		
		private string _P_Name;
		
		private string _P_Colour;
		
		private decimal _P_Price;
		
		private string _P_Img;
		
		private string _P_Type;
		
		private string _P_Size;
		
		private System.Nullable<System.DateTime> _P_Date;
		
		private string _P_Description;
		
		private string _P_Category;
		
		private System.Nullable<int> _P_Quantity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnP_IdChanging(int value);
    partial void OnP_IdChanged();
    partial void OnP_NameChanging(string value);
    partial void OnP_NameChanged();
    partial void OnP_ColourChanging(string value);
    partial void OnP_ColourChanged();
    partial void OnP_PriceChanging(decimal value);
    partial void OnP_PriceChanged();
    partial void OnP_ImgChanging(string value);
    partial void OnP_ImgChanged();
    partial void OnP_TypeChanging(string value);
    partial void OnP_TypeChanged();
    partial void OnP_SizeChanging(string value);
    partial void OnP_SizeChanged();
    partial void OnP_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnP_DateChanged();
    partial void OnP_DescriptionChanging(string value);
    partial void OnP_DescriptionChanged();
    partial void OnP_CategoryChanging(string value);
    partial void OnP_CategoryChanged();
    partial void OnP_QuantityChanging(System.Nullable<int> value);
    partial void OnP_QuantityChanged();
    #endregion
		
		public Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int P_Id
		{
			get
			{
				return this._P_Id;
			}
			set
			{
				if ((this._P_Id != value))
				{
					this.OnP_IdChanging(value);
					this.SendPropertyChanging();
					this._P_Id = value;
					this.SendPropertyChanged("P_Id");
					this.OnP_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string P_Name
		{
			get
			{
				return this._P_Name;
			}
			set
			{
				if ((this._P_Name != value))
				{
					this.OnP_NameChanging(value);
					this.SendPropertyChanging();
					this._P_Name = value;
					this.SendPropertyChanged("P_Name");
					this.OnP_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Colour", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string P_Colour
		{
			get
			{
				return this._P_Colour;
			}
			set
			{
				if ((this._P_Colour != value))
				{
					this.OnP_ColourChanging(value);
					this.SendPropertyChanging();
					this._P_Colour = value;
					this.SendPropertyChanged("P_Colour");
					this.OnP_ColourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Price", DbType="Money NOT NULL")]
		public decimal P_Price
		{
			get
			{
				return this._P_Price;
			}
			set
			{
				if ((this._P_Price != value))
				{
					this.OnP_PriceChanging(value);
					this.SendPropertyChanging();
					this._P_Price = value;
					this.SendPropertyChanged("P_Price");
					this.OnP_PriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Img", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string P_Img
		{
			get
			{
				return this._P_Img;
			}
			set
			{
				if ((this._P_Img != value))
				{
					this.OnP_ImgChanging(value);
					this.SendPropertyChanging();
					this._P_Img = value;
					this.SendPropertyChanged("P_Img");
					this.OnP_ImgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string P_Type
		{
			get
			{
				return this._P_Type;
			}
			set
			{
				if ((this._P_Type != value))
				{
					this.OnP_TypeChanging(value);
					this.SendPropertyChanging();
					this._P_Type = value;
					this.SendPropertyChanged("P_Type");
					this.OnP_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Size", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string P_Size
		{
			get
			{
				return this._P_Size;
			}
			set
			{
				if ((this._P_Size != value))
				{
					this.OnP_SizeChanging(value);
					this.SendPropertyChanging();
					this._P_Size = value;
					this.SendPropertyChanged("P_Size");
					this.OnP_SizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Date", DbType="Date")]
		public System.Nullable<System.DateTime> P_Date
		{
			get
			{
				return this._P_Date;
			}
			set
			{
				if ((this._P_Date != value))
				{
					this.OnP_DateChanging(value);
					this.SendPropertyChanging();
					this._P_Date = value;
					this.SendPropertyChanged("P_Date");
					this.OnP_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Description", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string P_Description
		{
			get
			{
				return this._P_Description;
			}
			set
			{
				if ((this._P_Description != value))
				{
					this.OnP_DescriptionChanging(value);
					this.SendPropertyChanging();
					this._P_Description = value;
					this.SendPropertyChanged("P_Description");
					this.OnP_DescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Category", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string P_Category
		{
			get
			{
				return this._P_Category;
			}
			set
			{
				if ((this._P_Category != value))
				{
					this.OnP_CategoryChanging(value);
					this.SendPropertyChanging();
					this._P_Category = value;
					this.SendPropertyChanged("P_Category");
					this.OnP_CategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Quantity", DbType="Int")]
		public System.Nullable<int> P_Quantity
		{
			get
			{
				return this._P_Quantity;
			}
			set
			{
				if ((this._P_Quantity != value))
				{
					this.OnP_QuantityChanging(value);
					this.SendPropertyChanging();
					this._P_Quantity = value;
					this.SendPropertyChanged("P_Quantity");
					this.OnP_QuantityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WishLIst")]
	public partial class WishLIst : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _P_Id;
		
		private string _P_Name;
		
		private int _User_ID;
		
		private decimal _P_Price;
		
		private string _P_Img;
		
		private string _P_Description;
		
		private System.DateTime _DateAdded;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnP_IdChanging(int value);
    partial void OnP_IdChanged();
    partial void OnP_NameChanging(string value);
    partial void OnP_NameChanged();
    partial void OnUser_IDChanging(int value);
    partial void OnUser_IDChanged();
    partial void OnP_PriceChanging(decimal value);
    partial void OnP_PriceChanged();
    partial void OnP_ImgChanging(string value);
    partial void OnP_ImgChanged();
    partial void OnP_DescriptionChanging(string value);
    partial void OnP_DescriptionChanged();
    partial void OnDateAddedChanging(System.DateTime value);
    partial void OnDateAddedChanged();
    #endregion
		
		public WishLIst()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Id", DbType="Int NOT NULL")]
		public int P_Id
		{
			get
			{
				return this._P_Id;
			}
			set
			{
				if ((this._P_Id != value))
				{
					this.OnP_IdChanging(value);
					this.SendPropertyChanging();
					this._P_Id = value;
					this.SendPropertyChanged("P_Id");
					this.OnP_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string P_Name
		{
			get
			{
				return this._P_Name;
			}
			set
			{
				if ((this._P_Name != value))
				{
					this.OnP_NameChanging(value);
					this.SendPropertyChanging();
					this._P_Name = value;
					this.SendPropertyChanged("P_Name");
					this.OnP_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="Int NOT NULL")]
		public int User_ID
		{
			get
			{
				return this._User_ID;
			}
			set
			{
				if ((this._User_ID != value))
				{
					this.OnUser_IDChanging(value);
					this.SendPropertyChanging();
					this._User_ID = value;
					this.SendPropertyChanged("User_ID");
					this.OnUser_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Price", DbType="Money NOT NULL")]
		public decimal P_Price
		{
			get
			{
				return this._P_Price;
			}
			set
			{
				if ((this._P_Price != value))
				{
					this.OnP_PriceChanging(value);
					this.SendPropertyChanging();
					this._P_Price = value;
					this.SendPropertyChanged("P_Price");
					this.OnP_PriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Img", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string P_Img
		{
			get
			{
				return this._P_Img;
			}
			set
			{
				if ((this._P_Img != value))
				{
					this.OnP_ImgChanging(value);
					this.SendPropertyChanging();
					this._P_Img = value;
					this.SendPropertyChanged("P_Img");
					this.OnP_ImgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Description", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string P_Description
		{
			get
			{
				return this._P_Description;
			}
			set
			{
				if ((this._P_Description != value))
				{
					this.OnP_DescriptionChanging(value);
					this.SendPropertyChanging();
					this._P_Description = value;
					this.SendPropertyChanged("P_Description");
					this.OnP_DescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateAdded", DbType="Date NOT NULL")]
		public System.DateTime DateAdded
		{
			get
			{
				return this._DateAdded;
			}
			set
			{
				if ((this._DateAdded != value))
				{
					this.OnDateAddedChanging(value);
					this.SendPropertyChanging();
					this._DateAdded = value;
					this.SendPropertyChanged("DateAdded");
					this.OnDateAddedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Invoice")]
	public partial class Invoice : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private decimal _Pds_TotPrice;
		
		private int _USER_ID;
		
		private System.DateTime _DATE;
		
		private string _PROD_IMAGE;
		
		private decimal _PROD_PRICE;
		
		private int _PROD_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnPds_TotPriceChanging(decimal value);
    partial void OnPds_TotPriceChanged();
    partial void OnUSER_IDChanging(int value);
    partial void OnUSER_IDChanged();
    partial void OnDATEChanging(System.DateTime value);
    partial void OnDATEChanged();
    partial void OnPROD_IMAGEChanging(string value);
    partial void OnPROD_IMAGEChanged();
    partial void OnPROD_PRICEChanging(decimal value);
    partial void OnPROD_PRICEChanged();
    partial void OnPROD_IDChanging(int value);
    partial void OnPROD_IDChanged();
    #endregion
		
		public Invoice()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pds_TotPrice", DbType="Money NOT NULL")]
		public decimal Pds_TotPrice
		{
			get
			{
				return this._Pds_TotPrice;
			}
			set
			{
				if ((this._Pds_TotPrice != value))
				{
					this.OnPds_TotPriceChanging(value);
					this.SendPropertyChanging();
					this._Pds_TotPrice = value;
					this.SendPropertyChanged("Pds_TotPrice");
					this.OnPds_TotPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_ID", DbType="Int NOT NULL")]
		public int USER_ID
		{
			get
			{
				return this._USER_ID;
			}
			set
			{
				if ((this._USER_ID != value))
				{
					this.OnUSER_IDChanging(value);
					this.SendPropertyChanging();
					this._USER_ID = value;
					this.SendPropertyChanged("USER_ID");
					this.OnUSER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE", DbType="Date NOT NULL")]
		public System.DateTime DATE
		{
			get
			{
				return this._DATE;
			}
			set
			{
				if ((this._DATE != value))
				{
					this.OnDATEChanging(value);
					this.SendPropertyChanging();
					this._DATE = value;
					this.SendPropertyChanged("DATE");
					this.OnDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROD_IMAGE", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string PROD_IMAGE
		{
			get
			{
				return this._PROD_IMAGE;
			}
			set
			{
				if ((this._PROD_IMAGE != value))
				{
					this.OnPROD_IMAGEChanging(value);
					this.SendPropertyChanging();
					this._PROD_IMAGE = value;
					this.SendPropertyChanged("PROD_IMAGE");
					this.OnPROD_IMAGEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROD_PRICE", DbType="Decimal(18,0) NOT NULL")]
		public decimal PROD_PRICE
		{
			get
			{
				return this._PROD_PRICE;
			}
			set
			{
				if ((this._PROD_PRICE != value))
				{
					this.OnPROD_PRICEChanging(value);
					this.SendPropertyChanging();
					this._PROD_PRICE = value;
					this.SendPropertyChanged("PROD_PRICE");
					this.OnPROD_PRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROD_ID", DbType="Int NOT NULL")]
		public int PROD_ID
		{
			get
			{
				return this._PROD_ID;
			}
			set
			{
				if ((this._PROD_ID != value))
				{
					this.OnPROD_IDChanging(value);
					this.SendPropertyChanging();
					this._PROD_ID = value;
					this.SendPropertyChanged("PROD_ID");
					this.OnPROD_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
